### ISSUE TITLE
arcade.get_image() get wrong crop of image

### ISSUE THREAD

**Issue by culurciello** [pvcraven/arcade#594]
Hi, in OS X I tried to use arcade.get_image() on a 256x256 window and it returns wrong crop. If I set window to arcade.get_image(0,0,512,512) it seems almost correct, but image, beside being larger of course, it it not a precise copy of window. Anyone has seen this?

**Comment by pvcraven** [comment]
Oh, that would be the retina display. Everything is scaled up. Get image needs to take that into account. 

In what way is the image different?

**Comment by culurciello** [comment]
I think it looks about right if I take a arcade.get_image(0,0,512,512) image - hard to tell. Maybe some diff because of menu bar on window. Do you know how to get the retina display issue fixed by any chance?

**Comment by pvcraven** [comment]
get_image needs to be updated to account for the resolution. Code should
look similar to get_pixel.

Paul Vincent Craven

**Comment by pvcraven** [comment]
This fix needs to be tested.

**Comment by pvcraven** [comment]
Arcade 2.3.9 is out, should be fixed now.
https://arcade.academy/release_notes.html

**Comment by liuyaanng** [comment]
Hi, i still have this situation with Arcade 2.3.10 in MacOS. But i tried to use `SCREEN_WIDTH * SCLALING` and `SCREEN_HEIGHT * SCALING` to instead `SCREEN_WIDTH` and `SCREEN_HEIGHT` when __init__ . It works in a smaller window and get the right size of images.

**Comment by pvcraven** [comment]
Hm, not sure what you mean. Can you provide a simple-as-possible example where you get an incorrect image?

**Comment by liuyaanng** [comment]
> Hm, not sure what you mean. Can you provide a simple-as-possible example where you get an incorrect image?

I try arcade.get_image() again today and i get an correct image. Thank you!😀

**Comment by liuyaanng** [comment]
> Hm, not sure what you mean. Can you provide a simple-as-possible example where you get an incorrect image?

I try arcade.get_image() again today and  get a correct picture of full wondow. But the size of image seems  incorrect. I use arcade.get_image() on a 600x800 window, but i get a 1200x1600 image which is too large for me.  So I set a parameter `RETINA_SCALING = 0.5` to zoom the window and the same to arcade.get_image(). Then i get the image with 600x800. This solved my problem. Anyway, thank you very much😃
